server {
    listen 80 default_server;
    server_name _;

    location /a/tecneuralai {
        proxy_pass http://127.0.0.1:3000/;
    }

    location /a/htcai {
        proxy_pass http://127.0.0.1:3000/;
    }

    location / {
        return 200 "NGINX is working";
    }
}